### PR TITLE
fix: import .tsx using import mapping

### LINKED ISSUE #4: Importing .tsx files does not work
### Package version

1.4.3

### Describe the bug

When importing .tsx files using a mapping import path it throws an error that module was not found.

Filename: `resources/views/emails/password.tsx`

```json [package.json]
{
  "imports": {
    "#emails/*": "./resources/views/emails/*.js"
  }
}
```

```ts
const Template = () => import('#emails/password')
```

This will work when builded, because tsc compiles file to `resources/views/emails/password.js`. But does not work using ts-exec, as it tries only .ts extension on error.

### Reproduction repo

_No response_

### PR DESCRIPTION
**Pull request by aadamcik**
### 🔗 Linked issue

#4 

### ❓ Type of change

- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Resolves #4 

### 📝 Checklist

- [x] I have read the [contribution guide](https://github.com/poppinss/.github/blob/main/docs/CONTRIBUTING.md).
- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/loader.ts [hunk 1]
```diff
@@ -112,22 +112,29 @@ export const resolve: ResolveHook = async (specifier, context, nextResolve) => {
...
-      return nextResolve(url, context)
+      for (const ext of testExtensions) {
+        const tryPath = urlPathname.slice(0, -fileExtension.length) + ext
+
+        try {
+          const url = urlQs.length ? `${tryPath}?${urlQs.join('?')}` : tryPath
+          debug('retrying to resolve file with specifier %s', url)
+          return await nextResolve(url, context)
+        } catch {
+          // ignore and try next extension
```
Comment (thetutlage) [inline src/loader.ts:135]: In this case, if the module is not found with any of the extensions, then we will miss the error?

Comment (aadamcik) [reply src/loader.ts:135]: No, it will throw the original error on line 140.
